//
// Created by Marvin Becker on 05.03.24.
//

/**
 * @file move.h
 * @brief Defines the Move structure and PseudoLegalMoves container used in the chess engine.
 *
 * This file encapsulates all move-related data structures, including representation
 * of individual moves, move types, and a fixed-capacity container for pseudo-legal moves
 * used during move generation and search.
 */

#pragma once
#include <algorithm>
#include <array>
#include <cassert>
#include <sstream>
#include <string>

#include "./core/piece.h"

// Represents the maximum of moves someone could possibly do.
constexpr int MAX_MOVES = 218;

/**
 * @brief Enumeration describing the type of a chess move.
 *
 * NORMAL       — simple move or capture
 * EN_PASSANT   — special pawn capture
 * PROMOTION    — pawn promotion into another piece
 * CASTLING     — king-side or queen-side castling
 */
enum MoveType : uint8_t { NORMAL, EN_PASSANT, PROMOTION, CASTLING };

/**
 * @brief Represents a single chess move in mailbox-coordinate form.
 *
 * Stores source and destination squares, piece information, captured pieces,
 * promotion choices, and the move type (normal, en passant, promotion, castling).
 * Provides utilities for comparison and algebraic-like string conversion.
 */
struct Move {
    // The square a piece want's to move to.
    int move_square_{0};

    // The square the piece is on.
    int square_{0};

    // The moving piece.
    Piece moving_piece_;

    // The piece which gets captured (If it is a normal move it will be EMPTY)
    Piece captured_piece_;

    // The piece a pawn can be promoted to. Can be empty.
    Piece promotion_piece_;

    // The type of move.
    MoveType move_type_{NORMAL};

    /**
     * @brief Converts the Move object to a uci readable string.
     *
     * This function takes the square and moveSquare coordinates of a Move object and converts them to
     * an uci readable format by using the coordinates of the square and the move_square.
     * If the move contained a PROMOTION, the promotion is also appended to the string.
     *
     * @return A string representation of the Move object.
     */
    [[nodiscard]] std::string to_string() const {
        std::ostringstream out;
        out << static_cast<char>((square_) % 8 + 'a') << (square_) / 8 + 1;
        out << static_cast<char>((move_square_) % 8 + 'a') << (move_square_) / 8 + 1;
        if (move_type_ == PROMOTION) {
            out << static_cast<char>(std::tolower(promotion_piece_.to_char()));
        }
        return out.str();
    }

    /**
     * @brief Overloaded equality operator for comparing two Move objects.
     *
     * @param other The other Move object to compare with.
     * @return True if the two Move objects are equal, false otherwise.
     */
    bool operator==(const Move& other) const {
        return move_square_ == other.move_square_ && square_ == other.square_ &&
               moving_piece_.piece_type_ == other.moving_piece_.piece_type_ &&
               captured_piece_.piece_type_ == other.captured_piece_.piece_type_ &&
               promotion_piece_.piece_type_ == other.promotion_piece_.piece_type_ && move_type_ == other.move_type_;
    }

    /**
     * @brief Check if a move is null.
     *
     * @return True if the Move is a null move.
     */
    [[nodiscard]] bool is_null() const
    {
        return move_square_ == 0 && square_ == 0;
    }
};

/**
 * @brief Container for storing moves generated by the move generator.
 *
 * Uses a fixed-size array for performance and cache locality. Moves are appended
 * in sequence, and the class provides iteration, indexing and containment checks.
 */
class MoveList {
    // Core array which will hold the moves.
    std::array<Move, MAX_MOVES> move_list_{};
    // The index of that array.
    int index_ = 0;

public:
    using iterator = std::array<Move, MAX_MOVES>::iterator;

    /**
     * @brief Get the number of elements in the MoveList.
     *
     * This function returns the max index of the MoveList (num. of elements).
     *
     * @return The number of elements in this list.
     */
    [[nodiscard]] int size() const {return index_;}

    /**
     * @fn iterator PseudoLegalMoves::begin()
     *
     * @brief Returns an iterator pointing to the first element in the move list.
     *
     * This function returns an iterator pointing to the first element in the move list.
     *
     * @return An iterator pointing to the first element in the move list.
     */
    iterator begin() { return move_list_.begin(); }

    /**
     * @fn iterator PseudoLegalMoves::end()
     *
     * @brief Returns an iterator one past the last element of the move list.
     *
     * This function returns an iterator pointing to one past the last element in the move list. It is used to indicate
     * the end of the range of elements in the move list.
     *
     * @return An iterator pointing to one past the last element of the move list.
     */
    iterator end() { return move_list_.begin() + index_; }

    /**
     * @brief Overloaded subscript operator for accessing a move in the move list.
     *
     * This function allows access to a move in the move list using the subscript operator [].
     * It performs index validation by asserting that the provided number is less than the index.
     * If the number is valid, the corresponding move is returned.
     *
     * @param number The index number of the desired move in the move list.
     * @return A reference to the move at the specified index.
     * @pre The move list must not be empty.
     * @pre Number must be less than the index.
     * @post None.
     */
    Move& operator[](const int number) {
        assert(number < index_);
        return move_list_[number];
    }

    /**
     * @brief Adds a move to the move list.
     *
     * This function adds a move to the move list by assigning it to the element at the current index. It then increments
     * the index by 1.
     *
     * @param mv The move to add to the move list.
     * @pre The index must be less than the maximum number of moves allowed.
     * @post The move is added to the move list and the index is incremented by 1.
     */
    void push_back(const Move& mv) {
        assert(index_ < MAX_MOVES);
        move_list_[index_] = mv;
        ++index_;
    }

    /**
     * @fn bool MoveList::contains(const Move& mv)
     *
     * @brief Checks if the MoveList contains a specified move.
     *
     * This function checks if the MoveList contains the specified move. It uses the std::find algorithm to search for
     * the move in the move list. If the move is found, it returns true; otherwise, it returns false.
     *
     * @param mv The move to check for in the move list.
     * @return True if the move list contains the specified move, false otherwise.
     */
    bool contains(const Move& mv) { return std::find(begin(), end(), mv) != end(); }
};
